{{- if .Values.backend.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: {{ include "ajasta-app.namespace" . }}
  labels:
    {{- include "ajasta-app.backend.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_PASSWORD: {{ .Values.backend.database.password | quote }}
  JWT_SECRET: {{ .Values.backend.secrets.jwtSecret | quote }}
  MAIL_USERNAME: {{ .Values.backend.secrets.mailUsername | quote }}
  MAIL_PASSWORD: {{ .Values.backend.secrets.mailPassword | quote }}
  AWS_ACCESS_KEY_ID: {{ .Values.backend.secrets.awsAccessKeyId | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.backend.secrets.awsSecretAccessKey | quote }}
  STRIPE_PUBLIC_KEY: {{ .Values.backend.secrets.stripePublicKey | quote }}
  STRIPE_SECRET_KEY: {{ .Values.backend.secrets.stripeSecretKey | quote }}
{{- end }}
