{{- if .Values.postgres.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: {{ include "ajasta-app.namespace" . }}
  labels:
    {{- include "ajasta-app.postgres.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_DB: {{ .Values.postgres.auth.database | quote }}
  POSTGRES_USER: {{ .Values.postgres.auth.username | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.auth.password | quote }}
{{- end }}
