{{- if .Values.rbac.create }}
{{- if .Values.rbac.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ajasta-app.serviceAccountName" . }}
  namespace: {{ include "ajasta-app.namespace" . }}
  labels:
    {{- include "ajasta-app.labels" . | nindent 4 }}
  {{- with .Values.rbac.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
